---
### Access-Lists ###
access_lists:
  - name: ACL-01
    sequence_numbers:
      - sequence: 10
        action: "remark ACL to restrict access to switch API to CVP and Ansible"
      - sequence: 20
        action: "deny ip host 192.0.2.1 any"
      - sequence: 30
        action: "permit ip 192.0.2.0/24 any"
  - name: ACL-02
    counters_per_entry: true
    permit_response_traffic: nat
    sequence_numbers:
      - sequence: 10
        action: "remark ACL to restrict access RFC1918 addresses"
      - sequence: 20
        action: "permit ip 10.0.0.0/8 any"
      - sequence: 30
        action: "permit ip 192.0.2.0/24 any"
  - name: ACL-03
    counters_per_entry: false
    sequence_numbers:
      - sequence: 10
        action: "remark ACL to restrict access RFC1918 addresses"
      - sequence: 20
        action: "deny ip 10.0.0.0/8 any"
      - sequence: 30
        action: "permit ip 192.0.2.0/24 any"
  - name: ACL-04
    counters_per_entry: true
    permit_response_traffic: nat
    sequence_numbers:
      - sequence: 20
        action: deny ip 12.0.0.0/8 any
      - sequence: 30
        action: permit ip 194.0.2.0/24 any
  - name: 4  # numeric ACL name
    counters_per_entry: false
    sequence_numbers:
      - sequence: 10
        action: "remark ACL to restrict access RFC1918 addresses"
      - sequence: 20
        action: "deny ip 10.0.0.0/8 any"
      - sequence: 30
        action: "permit ip 192.0.2.0/24 any"
